### ISSUE TITLE
Система друзей

### ISSUE THREAD

**Issue by AlexPolarBear** [spbu-math-cs/GiveGift-frontend#16]
Решить насчёт системы друзей / анонимной системы друзей. Сделать обработку входящих и исходящих друзей, или добавления их самостоятельно, в зависимости от системы.

**Comment by Amirelkanov** [comment]
Соответствующий фронт сделан
![image](https://github.com/spbu-math-cs/GiveGift-frontend/assets/57632427/45f2b9f0-db52-4c04-8dac-beea38a9c756)
